services:
  mongo: 
    image: mongo:7
    container_name: mongo 
    ports:
      - "27017:27017"

  frontend-container:
    image: harshapillari03/frontend-image:latest
    ports:
      - "8060:80"

  backend-container:
    image: harshapillari03/backend-image:latest
    ports:
      - "4000:4000"
    environment:
       MONGO_URI: mongodb://mongo:27017/todos
    depends_on:
      - mongo 
